const defaultSEOConfig = {  
    title: "Create Next App",  
    description: "Generated by create next app",  
    openGraph: {  
      type: "website",  
      locale: "vi_VN",  
      url: "https://www.example.com/",  
      site_name: "Create Next App",  
      images: [  
        {  
          url: "https://via.placeholder.com/1200x630",  
          width: 1200,  
          height: 630,  
          alt: "Create Next App",  
        },  
      ],  
    },  
    twitter: {  
      handle: "@example",  
      site: "@example",  
      cardType: "summary_large_image",  
    },  
  };  
  
  export default defaultSEOConfig;