
import "./globals.css";  
import { DefaultSeo } from "next-seo"; // Import DefaultSeo  
import defaultSEOConfig from "../../next-seo.config"; // Import cấu hình SEO  
 

export const metadata = {  
  title: "Create Next App",  
  description: "Generated by create next app",  
};  

export default function RootLayout({ children }) {  
  return (  
    <html lang="vi">  
      <body>  
        {/* Cấu hình SEO mặc định */}  
        {/* <DefaultSeo {...defaultSEOConfig} />  */}
        {children}  
      </body>  
    </html>  
  );  
}